version: '3.8'

services:
   postgres:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blog
      PGDATA: /var/lib/posgresql/data
    volumes:
      - db-data:/var/lib/posgresql/data:rw
    ports:
      - "5432:5432"
   php:
     build:
       context: .
       target: app_php
     image: blog/php:dev
     restart: on-failure
     environment:
       APP_ENV: dev
       APP_DEBUG: 1
       PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
     depends_on:
       - postgres
     volumes:
       - .:/app:rw,cached
       - var:/app/var:rw,cached

   nginx:
     build:
       context: .
       target: app_nginx
     image: blog/nginx:dev
     restart: on-failure
     depends_on:
       - php
     ports:
       - "8080:80"
     volumes:
       - ./public:/app/public:ro

volumes:
  db-data:
  var: