version: '3.8'

services:
   postgres:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blog
      PGDATA: /var/lib/posgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

   php:
     build:
       context: .docker/php
       dockerfile: Dockerfile
     restart: on-failure
     environment:
       APP_ENV: dev
       APP_DEBUG: 1
       PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
     depends_on:
       - postgres
     ports:
       - "9000:9000"
     user: "1000:1000"
     volumes:
       - ./app:/var/www/app

   nginx:
     image: nginx:1.21.0-alpine
     restart: on-failure
     ports:
       - "8000:80"
     volumes:
       - ./app:/var/www/app
       - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

   mailhog:
     image: mailhog/mailhog
     restart: on-failure
     ports:
       - "1025:1025"
       - "8025:8025"
     logging:
       driver: 'none'


volumes:
  postgres:
    driver: local